server:
  port: 8081
saml2:
  ap:
    metadata:
     location: http://localhost:8080/realms/OneLogin/protocol/saml/descriptor
    signing-cert: MIICoTCCAYkCBgGOhoPGBTANBgkqhkiG9w0BAQsFADAUMRIwEAYDVQQDDAlDdXN0b21lcjEwHhcNMjQwMzI4MTkyMTA2WhcNMzQwMzI4MTkyMjQ2WjAUMRIwEAYDVQQDDAlDdXN0b21lcjEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC46+G8Lj0GCjcg/eGVfCxjDUGr0OcbYQMbGhOrXzazcWBcAbWdfkA446cibzce1Jki3/zCPT5phfLAdUJF4aVBqLLPlJTXoj5teHCLlNGQZ9hTuoh24Ppqz5UHmUdfrMdxhBbwJ2UX5H7nDkjv1Z+h6Md1NUGnu6vLE7G807NQPWCq/pUDtqKcPW8xnqdpKmKvPyx2rDT2o+WMcgl/cslvIRceJdaslXuExpq0wSdATfdNNc6AbEm68ZHhT8Nov4/hczwWrONmhZ/MA4HYbpS61zNUotrH+OXyt6IzjP1o4fAn08736EJELmq96EQ+V7lVH10vgm2YZVv4TkBe6kVvAgMBAAEwDQYJKoZIhvcNAQELBQADggEBADwosE17rE1zq1gxqE39zRRusCJNAutvz0VgPQEwxfsSEcSrENntQXDc5hTrU+NKS2e+9kdr8fJB4QdAiyaD+tqCRu4y1KXtAr5s81I4RModZQlxS4ryxMfxUpte4S1uGQVC25V8fvv8FZygrJh4dWSl8oX228506nCzn37hfvXIuv1nfUzZNyPxAHvhN4RNBGLC5BPZPvTzfhHHqSCwyhiGsq7gBNMIWBVCTEEcSWeyTzedG3DgDHEswQEFgK4j5yFTQqKBLx5MDw7Xk77KHXNMDKxjsO3QY2nwUByzw4MEo9OuSWCgOZCvY/0U717E3igoplua28unVB7qL68FzMc=

